### ISSUE TITLE
Remove vecnet.openmalaria.input package

### ISSUE THREAD

**Issue by Baguage** [vecnet/vecnet.openmalaria#20]
This package implements XmlInputFile class, and it has been superseded by vecnet.openmalaria.scenario package. I consider vecnet.openmalaria.input API depricated.

**Comment by sgtbigman** [comment]
Should we consider phasing it out (and making it obsolete) as soon as possible, or wait until v0.9 or v1.0?

**Comment by Baguage** [comment]
I think we should. vnetsource is no longer using it, so it should be safe.

**Comment by sgtbigman** [comment]
I agree, and I do not believe we have any other users of the package at the moment that would be affected by the removal. I will go ahead with removing the input API for the next version.

**Comment by Baguage** [comment]
sounds good. do not remove input files for input_tests just yet, they can be used by Scenario tests
