### ISSUE TITLE
Removing last intervention in human or vectorPop sections invalidates xml.

### ISSUE THREAD

**Issue by sgtbigman** [vecnet/vecnet.openmalaria#41]
`<human>/<vectorPop>` sections need removed if the last `<component>/<intervention>` is removed from them.

**Comment by nicolasreed** [comment]
The CI site will check for this and remove the section(s) for now.

Eventually, it would be nice to implement the [Observer Pattern](https://en.wikipedia.org/wiki/Observer_pattern) for the entire project, so that these types of issues are automatically handled.
